version: "3.9"
services:
  planner:
    build:
      context: .
      dockerfile: Dockerfile
    image: travel-planner:dev
    container_name: travel-planner
    env_file: .env
    environment:
      - APP_ENV=local
      - LANGCHAIN_TRACING_V2=true
    ports:
      - "8000:8000"
    volumes:
      - ./data/cache:/app/data/cache
      - ./prompts:/app/prompts:ro
    restart: unless-stopped
